import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { ConfigIntegrityGuardLaw } from '../../src/checkers/meta-gate-laws/config-integrity-guard';
import { isNonLawConfigKey } from '../../src/utils/law-identity';
import { FileUtils } from '../../src/utils';
import type { RuleOfCodeConfig } from '../../src/types/law.types';

/**
 * JSON has no comment syntax. A `$`-prefixed key is the conventional way to
 * annotate a map, and `$comment` is a JSON Schema keyword.
 *
 * `laws.notApplicable` is the one section where every entry is a human decision
 * that needs explaining — and an explanation there was reported as an
 * unresolvable law name: a violation that failed the audit outright, and a
 * warning on every single run when the same annotations appeared in
 * `ignores.byRule`.
 *
 * A key that cannot be a law name is not a typo'd law name.
 */
describe('a $-annotation in a config map is not a law name', () => {
  let root: string;

  const withLaws = (laws: Record<string, unknown>): RuleOfCodeConfig => {
    const config = FileUtils.getMinimalDefaultConfig();
    config.laws = { ...config.laws, ...laws } as RuleOfCodeConfig['laws'];
    return config;
  };

  const findings = (config: RuleOfCodeConfig): string[] => {
    const result = ConfigIntegrityGuardLaw.check({
      projectRoot: root,
      config,
      lawId: 'config-integrity-guard',
    });
    return result.violations ?? [];
  };

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), 'roc-annot-'));
    fs.writeFileSync(path.join(root, 'package.json'), '{"name":"x"}');
  });
  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true });
  });

  describe('the predicate itself', () => {
    it.each([['$comment'], ['$comment-logger'], ['$note'], ['law-42']])(
      '%s is not a law name',
      key => {
        expect(isNonLawConfigKey(key)).toBe(true);
      }
    );

    it.each([['centralized-logging'], ['law-of-the-land'], ['comment']])(
      '%s is treated as a law name',
      key => {
        expect(isNonLawConfigKey(key)).toBe(false);
      }
    );
  });

  it.each([['notApplicable'], ['severity'], ['enabled']])(
    'accepts an annotation in laws.%s',
    section => {
      expect(
        findings(withLaws({ [section]: { $comment: 'why, for a human' } }))
      ).toEqual([]);
    }
  );

  it('accepts several suffixed annotations in one map', () => {
    expect(
      findings(
        withLaws({
          notApplicable: {
            $comment: 'the section as a whole',
            '$comment-logger': 'about the logging entry',
            '$comment-origins': 'about the origins entry',
          },
        })
      )
    ).toEqual([]);
  });

  it('still accepts the legacy autogenerated shape', () => {
    expect(findings(withLaws({ notApplicable: { 'law-42': 'legacy' } }))).toEqual(
      []
    );
  });

  /**
   * The red controls. This law exists to catch a key that gates nothing while
   * the config looks strict — widening it must not blunt that.
   */
  it('still reports a misspelt law name', () => {
    const reported = findings(
      withLaws({ notApplicable: { 'centralised-logging': 'misspelt' } })
    );

    expect(reported.length).toBeGreaterThan(0);
    expect(reported[0]).toMatch(/centralised-logging/);
  });

  it('still reports a name that merely contains a dollar sign', () => {
    expect(
      findings(withLaws({ notApplicable: { 'logging$comment': 'not a prefix' } }))
        .length
    ).toBeGreaterThan(0);
  });

  it('says nothing about a real law name', () => {
    expect(
      findings(
        withLaws({ notApplicable: { 'centralized-logging': 'no server here' } })
      )
    ).toEqual([]);
  });
});
