/**
 * Meta-Gate Laws Data Module
 * Laws about the integrity of the gate itself — dogfooding from RoC's own
 * field incidents (v7.5.0 severity disarm, v7.5.1 zero-laws-checked P0),
 * proposed by an architecture audit (2026-07-11). Universal (no
 * stack), error severity from day one: the gate of the gate is not warn-first.
 * legacyId range: 226+ (batch 1 of the arch proposal).
 */

import type { EnhancedConstitutionalLaw } from '../types/enhanced-law.types';
import { generateLawId } from '../utils/id-generator';

export const META_GATE_LAWS: EnhancedConstitutionalLaw[] = [
  {
    id: generateLawId(
      'Audit Liveness Assertion',
      'The audit fails when it executes fewer laws than the liveness floor',
      'meta'
    ),
    legacyId: 226,
    article: 'I',
    subsection: '1.90',
    title: 'Audit Liveness Assertion',
    rationale:
      'v7.5.1 shipped an audit that executed ZERO laws and printed PASSED, exit 0. A config that selects nothing looks identical to a clean pass — a silently disarmed gate is more dangerous than a missing one, because it hands you unearned confidence. This law refuses to report compliance when the executed law count collapses below the floor.',
    satisfiedBy: {
      typescript:
        'Set laws.minLawsChecked to your real post-waiver count; never let laws.enabled / paretoMode shrink the set below it.',
      python:
        'Same: pin laws.minLawsChecked to the number you expect to run, so a broken config fails loudly instead of passing empty.',
    },
    detectionLimits: [
      'It counts the number of PLANNED laws, not whether each one actually inspected any code — a stack-gated law that runs and passes vacuously still counts toward the floor.',
      'When laws.enabled or paretoMode is set the default 25% floor drops to zero, so unless you also pin laws.minLawsChecked a deliberately narrowed set of one law passes; only the engine hard-zero refusal remains.',
      'It asserts a count, not identities — swapping which laws run, as long as the total stays above the floor, is invisible to it.',
    ],
    emoji: '💓',
    description:
      'The audit fails when it plans fewer laws than the liveness floor (laws.minLawsChecked, default 25% of stack-applicable) — a collapsed selection is a disarmed gate, never compliance',
    priority: 'CRITICAL',
    category: 'SECURITY',
    defaultEnabled: true,
    defaultSeverity: 'error',
    automation: 'AUTOMATED',
    checkFunction: 'AuditLivenessLaw.check',
    alwaysEnabled: true,
    violationMessage:
      'CONSTITUTIONAL VIOLATION Article I.1.90: Audit executed fewer laws than the liveness floor',
    remediation:
      'Check laws.enabled/notApplicable/paretoMode for a collapsed selection; set laws.minLawsChecked to your known post-waiver count',
  },

  {
    id: generateLawId(
      'Config Integrity Guard',
      'Unknown law keys in severity/notApplicable/enabled are findings, not silence',
      'meta'
    ),
    legacyId: 227,
    article: 'I',
    subsection: '1.91',
    title: 'Config Integrity Guard',
    rationale:
      'A typo\'d or stale key in laws.severity / notApplicable / enabled gates nothing — the config looks strict while the gate is disarmed (v7.5.0). Worse, a key that resolves to MORE THAN ONE law (25 legacyIds are shared by 51 laws) silences several while the team thinks it silenced one: a hidden waiver. This law makes an unknown or ambiguous key a finding, so the config fails loudly instead of lying quietly.',
    satisfiedBy: {
      typescript:
        'Key config by canonical name or slug, never legacyId; each key must resolve to exactly one law (see configKeys in `roc laws --json`).',
      python:
        'Same: name the law explicitly; remove entries for laws that no longer exist.',
    },
    detectionLimits: [
      'It validates only keys under laws.severity / laws.notApplicable / laws.enabled; a typo in any other config section (thresholds, ignores, project) is not checked.',
      'It flags unknown or ambiguous keys, not wrong VALUES — a key that resolves to exactly one law but sets an inappropriate severity or a bogus notApplicable reason passes.',
      'Keys matching the autogenerated law-<n> pattern are skipped entirely, so a stale entry in that legacy form is not caught, and a correctly-resolving key is accepted even when the waiver behind it is unjustified.',
    ],
    emoji: '🔏',
    description:
      'A laws.severity / laws.notApplicable / laws.enabled key that matches no law identity is a finding — a typo’d override gates nothing while the config looks strict (stack-gated laws remain legitimate)',
    priority: 'CRITICAL',
    category: 'SECURITY',
    defaultEnabled: true,
    defaultSeverity: 'error',
    automation: 'AUTOMATED',
    checkFunction: 'ConfigIntegrityGuardLaw.check',
    alwaysEnabled: true,
    violationMessage:
      'CONSTITUTIONAL VIOLATION Article I.1.91: Config references an unknown law',
    remediation:
      "Fix the key (canonical name / printed slug / id / legacyId all resolve — see 'roc laws --list') or remove the stale entry",
  },

  {
    id: generateLawId(
      'Golden Fixture Immutability',
      'Changing declared golden fixtures requires an explicit approval entry',
      'meta'
    ),
    legacyId: 232,
    article: 'I',
    subsection: '1.92',
    title: 'Golden Fixture Immutability',
    rationale:
      'A golden/snapshot file is the recorded truth a test compares against — change it silently and you have not fixed the test, you have moved the goalpost. This law makes updating a golden a deliberate, reviewed act.',
    satisfiedBy: {
      typescript:
        'Declare your golden/snapshot paths in config.goldenPaths; when you legitimately update one, record the approval in GOLDEN-APPROVALS.md in the same change.',
      python:
        'Same — declare the golden paths and record the approval; the check is git-based and language-agnostic.',
    },
    detectionLimits: [
      'Does not read fixture CONTENT — it cannot tell a legitimate update from a masked regression; touching GOLDEN-APPROVALS.md (even trivially) fully satisfies it.',
      'Opt-in: with no config.goldenPaths — and with no git repo — it always passes.',
      'Sees only the current diff window (working tree + unpushed); a golden changed in already-pushed history is invisible.',
    ],
    emoji: '🥇',
    description:
      'Changes under the declared goldenPaths require a GOLDEN-APPROVALS.md entry in the same change-set — a silent snapshot regen masks a regression (configurable; without goldenPaths the law passes; applies to JS snapshots too)',
    priority: 'HIGH',
    category: 'TESTING',
    defaultEnabled: true,
    defaultSeverity: 'error',
    automation: 'CONFIGURABLE',
    checkFunction: 'GoldenFixtureImmutabilityLaw.check',
    violationMessage:
      'CONSTITUTIONAL VIOLATION Article I.1.92: Golden fixture changed without an approval entry',
    remediation:
      'Record the regen in GOLDEN-APPROVALS.md (what/why/approver) in the same change-set — or fix the code instead of re-blessing the output',
  },
];
